from django.urls import path
from . import views

app_name = 'admin_control'

urlpatterns = [
    path('', views.admin_dashboard, name='dashboard'),
    path('products/', views.manage_products, name='manage_products'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/edit/<int:pk>/', views.edit_product, name='edit_product'),
    path('products/delete/<int:pk>/', views.delete_product, name='delete_product'),
    path('products/view/<int:pk>/', views.view_product, name='view_product'),
    path('categories/', views.manage_categories, name='manage_categories'),
    path('categories/add/', views.add_category, name='add_category'),
    path('categories/edit/<int:pk>/', views.edit_category, name='edit_category'),
    path('categories/delete/<int:pk>/', views.delete_category, name='delete_category'),
    path('orders/', views.manage_orders, name='manage_orders'),
    path('orders/view/<int:order_id>/', views.view_order_details, name='view_order_details'),
    path('orders/update/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('orders/print/<int:order_id>/', views.print_order, name='print_order'),
    path('users/', views.manage_users, name='manage_users'),
    path('users/add/', views.add_user, name='add_user'),
    path('users/view/<int:pk>/', views.view_user, name='view_user'),
    path('users/edit/<int:pk>/', views.edit_user, name='edit_user'),
    path('users/toggle-status/<int:pk>/', views.toggle_user_status, name='toggle_user_status'),
    path('users/delete/<int:pk>/', views.delete_user, name='delete_user'),
    path('content/', views.manage_content, name='manage_content'),
    path('content/blog/<slug:slug>/', views.admin_blog_detail, name='admin_blog_detail'),
    path('content/blog/delete/<int:blog_id>/', views.delete_blog_post, name='delete_blog_post'),
    path('content/video/delete/<int:video_id>/', views.delete_video_post, name='delete_video_post'),
    path('notifications/', views.all_notifications, name='all_notifications'),
    path('notifications/mark-read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('notifications/dismiss/<int:notification_id>/', views.dismiss_notification, name='dismiss_notification'),
    path('notifications/api/unread-count/', views.get_unread_count, name='get_unread_count'),
    path('chat/', views.admin_chat, name='admin_chat'),
    path('chat/room/<int:room_id>/', views.admin_chat_room, name='admin_chat_room'),
    path('chat/api/send/', views.admin_send_message, name='admin_send_message'),
    path('chat/api/messages/<int:room_id>/', views.admin_get_messages, name='admin_get_messages'),
    path('chat/api/rooms/', views.get_chat_rooms, name='get_chat_rooms'),
    path('profile/', views.admin_profile, name='profile'),
    path('analytics/', views.analytics, name='analytics'),
    path('analytics/export/', views.export_analytics, name='export_analytics'),
    path('settings/api/', views.api_settings, name='api_settings'),
    path('payments/', views.manage_payments, name='manage_payments'),
    path('payments/view/<int:payment_id>/', views.view_payment_details, name='view_payment_details'),
    path('payments/refund/<int:payment_id>/', views.process_refund, name='process_refund'),
]