# Generated by Django 4.2.7 on 2025-07-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_remove_product_type'),
        ('order_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
