# Generated by Django 4.2.7 on 2025-07-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0002_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
