# Generated by Django 4.2.7 on 2025-07-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0004_alter_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
