# Generated by Django 4.2.7 on 2025-07-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0005_remove_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='special_instructions',
        ),
    ]
