# Generated by Django 4.2.7 on 2025-07-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0006_remove_order_special_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address_text',
        ),
    ]
