# Generated by Django 4.2.7 on 2025-07-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interaction', '0002_reviewhelpful'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='blog_videos/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video (YouTube, Vimeo, etc.)'),
        ),
    ]
