# Generated by Django 4.2.7 on 2025-07-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interaction', '0003_blogpost_video_file_blogpost_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='video_url',
        ),
        migrations.DeleteModel(
            name='ReviewHelpful',
        ),
    ]
