# Generated by Django 4.2.7 on 2025-07-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interaction', '0004_remove_blogpost_video_file_remove_blogpost_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image',
        ),
    ]
