# Generated by Django 4.2.7 on 2025-07-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interaction', '0007_blogpost_is_published_blogpost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
    ]
