# Generated by Django 4.2.7 on 2025-07-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interaction', '0009_delete_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
