# Generated by Django 4.2.7 on 2025-07-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('order_placed', 'New Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_status', 'Order Status Update'), ('low_stock', 'Low Stock Alert'), ('user_registered', 'New User Registration'), ('welcome', 'Welcome Message'), ('support_ticket', 'New Support Ticket'), ('support_replied', 'Support Ticket Reply'), ('support_resolved', 'Support Ticket Resolved'), ('blog_submitted', 'Blog Post Submitted'), ('blog_approved', 'Blog Post Approved'), ('blog_rejected', 'Blog Post Rejected'), ('product_added', 'New Product Added'), ('promotional', 'Promotional'), ('reminder', 'Reminder'), ('system', 'System Notification')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate when notification is clicked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='admin_contr_recipie_34f25d_idx'), models.Index(fields=['notification_type'], name='admin_contr_notific_4b1667_idx'), models.Index(fields=['created_at'], name='admin_contr_created_7438cf_idx')],
            },
        ),
    ]
